### ISSUE TITLE
Uninstalling the helm chart is removing the clickhouse pvc

### ISSUE THREAD

**Issue by manishrawat1992** [Altinity/helm-charts#38]
When we delete the helm chart the clickhouse pvc's are also deleted alongwith it only pv remain in released state. 

This is not the expected behavior. We wanted to have pvc's intact so that we can recreate the cluster by reinstalling

**Comment by manishrawat1992** [comment]
Operator changes are too fast and its hard to track all the changes here. 

It seems the reclaim policy only works if storageProvisioner is Operator

```
 defaults:
    storageManagement:
      reclaimPolicy: Retain
      provisioner: Operator
```

**Comment by manishrawat1992** [comment]
Thank you so much @denisok

**Comment by Berodin** [comment]
@manishrawat1992 out of interest, were you able to reproduce it with the adjusted template?

**Comment by joshleecreates** [comment]
@manishrawat1992 Let us know if this is still an issue. I've run a few tests and haven't been able to recreate this.

**Comment by kerthcet** [comment]
Hi, I'm using the latest v0.27.0, seems like the clickhouse pvc will always be deleted even set the reclaimPolicy as suggested like:
```
    volumeClaimTemplates:
      - name: data-volume
        # Retain PVCs when ClickHouseInstallation is deleted to preserve data
        reclaimPolicy: Retain
        spec:
          storageClassName: {{ .Values.clickhouse.storage.className }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.storage.size }}
```
